Mainpage/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('',views.Homepage,name="Homepage"),
    path('about/',views.AboutPage,name="AboutPage"),
    path('designs/',views.DesignPage,name="DesignPage"),
    path('profile/',views.ProfilePage,name="ProfilePage"),
    path('add-design/',views.AddDesignPage,name="AddDesignPage"),
    path('mydesign/<id>/',views.MyDesignPage,name="MyDesignPage"),
    path('user-info/<id>/',views.UserInformation,name="UserInformation"),
    path('all-user/',views.All_User,name="All_User"),
    path('appointments/',views.Appointments,name="Appointments"),
    path('pending-app/',views.PendingAppointment,name="PendingAppointment"),
    path('edit-profile/',views.Edit_Profile,name='Edit_Profile'),
    path('contact/',views.ContactPage,name="ContactPage"),
    path('main-user-info/<id>',views.MainUserInfo,name="MainUserInfo"),
    path('checkout/',views.Checkout,name='Checkout'), # type: ignore
    path('success/',views.success_page,name="success_page"),
    path('cancle/',views.cancle_page,name="cancle_page"),
    path('logout/',views.Logout,name="Logout"),
    path('contract-status/',views.Contract_Status,name="Contract_Status"), # type: ignore
    path('add-payment/',views.PaymentManager,name="PaymentManager"), # type: ignore
    path('paymentsuccess/',views.Paymentsuccess,name="Paymentsuccess"),
    path('payment-checkout/',views.PaymentCheckout,name="PaymentCheckout"), # type: ignore
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

SERVICE_SYS/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Mainpage.urls')),
    path('',include('Loginsystem.urls')),
]

Mainpage/models.py
from django.db import models
import datetime


class AccountData(models.Model):
    acc_id = models.IntegerField(default=0)
    email = models.EmailField(max_length=100,default="")
    acc_type = models.TextField(max_length=100,default="")
    architech_fees = models.IntegerField(default=0)

    def __str__(self):
        return str(self.acc_id) + " - " + self.acc_type
    
class DesignData(models.Model):
    design_id = models.AutoField
    user_id = models.IntegerField(default=0)
    design_img = models.ImageField(upload_to="design_img/")
    design_type = models.TextField(max_length=50,default="")
    project_name = models.TextField(max_length=200,default="")
    design_desc = models.TextField(max_length=5000,default="")
    user_type = models.TextField(max_length=50,default="")

    def __str__(self):
        return str(self.user_id) + " - " + self.design_type
    
class AppointmentData(models.Model):
    appointment_id = models.AutoField
    appointment_date = models.DateField(default=datetime.date.today)
    start_time = models.TextField(max_length=50,default="")
    end_time = models.TextField(max_length=50,default="")
    appointment_desc = models.TextField(max_length=500,default="")
    architech_id = models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    architech_name = models.TextField(max_length=100,default="")
    consumer_name = models.TextField(max_length=150,default="")
    status = models.TextField(max_length=40,default="In Waiting")

    def __str__(self):
        return str(self.architech_id) + " - " + str(self.user_id)
    
class contactform(models.Model):
    contact_id = models.AutoField
    email_id = models.EmailField(max_length=100,default="")
    message = models.TextField(max_length=500,default="")

    def __str__(self):
        return self.email_id
    
class Temp_appointment(models.Model):
    user_id = models.IntegerField(default=0)
    appointment_date = models.DateField(default=datetime.date.today)
    start_time = models.TextField(max_length=50,default="")
    end_time = models.TextField(max_length=50,default="")
    appointment_desc = models.TextField(max_length=500,default="")
    architech_id = models.IntegerField(default=0)


class PaymentData(models.Model):
    payment_id = models.AutoField
    appointment_id = models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    architech_id = models.IntegerField(default=0)
    payment = models.IntegerField(default=0)

class TempPayment(models.Model):
    amount = models.IntegerField(default=0)
    app_id = models.IntegerField(default=0)
    architech_id = models.IntegerField(default=0)

Mainpage/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import AccountData,DesignData,AppointmentData,contactform,Temp_appointment,PaymentData,TempPayment
import stripe


def Homepage(request):
    if request.method == "POST":
        fname = request.POST.get("fname")
        lname = request.POST.get("lname")
        email = request.POST.get("email")
        mobile = request.POST.get("mobile")
        password = request.POST.get("pass")
        acctype = request.POST.get("acctype")
        print(acctype)
        cpass = request.POST.get("cpass")
        if password == cpass:
            myuser = User.objects.create_user(email,mobile,password)
            myuser.first_name = fname
            myuser.last_name = lname
            myuser.save()
            user = authenticate(username = email,password = password)
            login(request,user)
            account_data = AccountData(acc_id = request.user.id,email = email,acc_type = acctype)
            account_data.save()
            messages.success(request,"You are Logged in successfully")
            type = acctype
            return render(request,"Mainpage/index.html",{"type":type})
        else:
            messages.warning(request,"Password is not matched ")
            return redirect("/password/")
    if request.user.is_authenticated == True:
        accout_data = AccountData.objects.filter(email = request.user).values()[0]
        type = accout_data["acc_type"]
        return render(request,"Mainpage/index.html",{"type":type})
    else:
        return render(request,"Mainpage/index.html")

def AboutPage(request):
    if request.user.is_authenticated == True:
        accout_data = AccountData.objects.filter(email = request.user).values()[0]
        type = accout_data["acc_type"]
        return render(request,"Mainpage/about.html",{"type":type})
    else:
        return render(request,"Mainpage/about.html")

def DesignPage(request):
    if request.user.is_authenticated == True:
        accout_data = AccountData.objects.filter(email = request.user).values()[0]
        type = accout_data["acc_type"]
        design_data = DesignData.objects.filter(user_type = "Architech").all().values()
        return render(request,"Mainpage/design.html",{"type":type,"design_data":design_data})
    else:
        return redirect("/login/")

def ProfilePage(request):
    if request.user.is_authenticated==True:
        accout_data = AccountData.objects.filter(email = request.user).values()[0]
        type = accout_data["acc_type"]
        designs = DesignData.objects.filter(user_id = request.user.id).values()
        return render(request,"Mainpage/profile.html",{"type":type,"designs":designs})
    else:
        return redirect("/login/")

def AddDesignPage(request):
    if request.user.is_authenticated == True:
        accout_data = AccountData.objects.filter(email = request.user).values()[0]
        type = accout_data["acc_type"]
        if request.method == "POST":
            design_type = request.POST.get("design_type")
            design_desc = request.POST.get("design_desc")
            project_name = request.POST.get("project_name")
            design_data = DesignData()
            design_data.user_id = request.user.id
            design_data.design_type = design_type
            design_data.design_desc = design_desc
            design_data.project_name = project_name
            design_data.user_type = type
            if len(request.FILES) != 0:
                design_data.design_img = request.FILES['design_img']
            design_data.save()
            messages.success(request,"Your Design is added successfully.")
        customer_data = AccountData.objects.filter(acc_type = "Consumer").all().values()
        users_data = []
        for i in customer_data:
            mydic = {}
            user_data = User.objects.filter(username = i["email"]).values()[0]
            mydic["id"] = user_data["id"]
            mydic["first_name"] = user_data["first_name"]
            mydic["last_name"] = user_data["last_name"]
            mydic["email"] = user_data["username"]
            mydic["mobile"] = user_data["email"]
            users_data.append(mydic)
            
        return render(request,"Mainpage/add-design.html",{"type":type,"customer_data":users_data})
    else:
        messages.warning(request,"First login after then book the consulatation")
        return redirect("/login/")

def MyDesignPage(request,id):
    if request.user.is_authenticated == True:
        accout_data = AccountData.objects.filter(email = request.user).values()[0]
        type = accout_data["acc_type"]
        design_data = DesignData.objects.filter(id = id).values()
        design_list = []
        for i in design_data:
            mydic = {}
            mydic["id"] = i["id"]
            mydic["design_img"] = i["design_img"]
            mydic["design_type"] = i["design_type"]
            mydic["project_name"] = i["project_name"]
            mydic["design_desc"] = i["design_desc"]
            mydic["user_type"] = i["user_type"]
            user_id = i["user_id"]
            user_data = User.objects.filter(id = user_id).values()[0]
            mydic["user_id"] = i["user_id"]
            mydic["email"] = user_data["username"]
            mydic["first_name"] = user_data["first_name"]
            mydic["last_name"] = user_data["last_name"]
            mydic["mobile"] = user_data["email"]
            design_list.append(mydic)
        return render(request,"Mainpage/mydesign.html",{"design_data":design_list,"type":type})
    else:
        return redirect("/login/")

def UserInformation(request,id):
    if request.user.is_authenticated==True:
        accout_data = AccountData.objects.filter(acc_id = request.user.id).values()[0]
        type = accout_data["acc_type"]
        user_data = User.objects.filter(id = id).values()
        designs = DesignData.objects.filter(user_id = id).values()
        type_data = AccountData.objects.filter(acc_id = id).values()[0]
        account_type = type_data["acc_type"]
        fees = type_data["architech_fees"]
        return render(request,"Mainpage/user-info.html",{"type":type,"accounts_data":user_data,"account_type":account_type,"designs":designs,"user_id":id,"fees":fees})
    else:
        return redirect("/login/")

def MainUserInfo(request,id):
    if request.user.is_authenticated==True:
        accout_data = AccountData.objects.filter(acc_id = request.user.id).values()[0]
        type = accout_data["acc_type"]
        user_data = User.objects.filter(id = id).values()
        designs = DesignData.objects.filter(user_id = id).values()
        type_data = AccountData.objects.filter(acc_id = id).values()[0]
        account_type = type_data["acc_type"]
        fees = type_data["architech_fees"]
        return render(request,"Mainpage/main-user-info.html",{"type":type,"accounts_data":user_data,"account_type":account_type,"designs":designs,"user_id":id,"fees":fees})
    else:
        return redirect("/login/")

def All_User(request):
    if request.user.is_authenticated:
        accout_data = AccountData.objects.filter(acc_id = request.user.id).values()[0]
        type = accout_data["acc_type"]
        user_type = AccountData.objects.filter(acc_id = request.user.id).values()[0]["acc_type"]
        if user_type == "Architech":
            account_data = AccountData.objects.filter(acc_type = "Consumer").all().values()
            user_list = []
            for i in account_data:
                mydic = {}
                id = i["acc_id"]
                mydic["id"] = id
                user_data = User.objects.filter(id = id).values()[0]
                mydic["first_name"] = user_data["first_name"]
                mydic["last_name"] = user_data["last_name"]
                mydic["number"] = user_data["email"]
                mydic["email"] = user_data["username"]
                mydic["acc_type"] = i["acc_type"]
                user_list.append(mydic)
            return render(request,"Mainpage/all_user.html",{"user_list":user_list,"type":type})
        else:
            account_data = AccountData.objects.filter(acc_type = "Architech").all().values()
            user_list = []
            for i in account_data:
                mydic = {}
                id = i["acc_id"]
                mydic["id"] = id
                user_data = User.objects.filter(id = id).values()[0]
                mydic["first_name"] = user_data["first_name"]
                mydic["last_name"] = user_data["last_name"]
                mydic["number"] = user_data["email"]
                mydic["email"] = user_data["username"]
                user_list.append(mydic)
            return render(request,"Mainpage/all_user.html",{"user_list":user_list,"type":type})
    else:
        return redirect("/login/")

def Appointments(request):
    if request.user.is_authenticated:
        accout_data = AccountData.objects.filter(acc_id = request.user.id).values()[0]
        payment_data = PaymentData.objects.all()
        type = accout_data["acc_type"]
        appointment_data = AppointmentData.objects.filter(user_id = request.user.id).all().values()
        return render(request,"Mainpage/appointment.html",{"appointment_data":appointment_data,"type":type,"payment_data":payment_data})
    else:
        return redirect("/login/")

def PendingAppointment(request):
    if request.user.is_authenticated:
        accout_data = AccountData.objects.filter(acc_id = request.user.id).values()[0]
        type = accout_data["acc_type"]
        appointments = AppointmentData.objects.filter(architech_id = request.user.id).all().values()
        if request.method == "POST":
            id = request.POST.get("id")
            data = id.split(" ")
            AppointmentData.objects.filter(id = data[0]).update(status = data[1])
            return redirect("/pending-app/")

Mainpage/templates/Mainpage/about.html
{% extends 'Mainpage/basic.html' %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %} About - ArcDesk {% endblock %}
    <link href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% block style %}
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Tilt+Neon&display=swap');
        body{
            background-color: white;
        }
        .main-container {
            margin-top: 150px;
            background-color: white;
            margin-bottom: 30px;
        }
        .main-container h2{
            text-align: center;
        }
        .main-container .content{
            height: auto;
            margin-top: 50px;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            align-items: center;
        }
        .main-container .content .part1{
            height: 100%;
            width: 50%;
        }
        .main-container .content .part1 img{
            width: 100%;
        }
        .main-container .content .part2{
            height: 100%;
            width: 50%;
            color: black;
            padding: 10px;
        }
        .main-container .content2{
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
        }
        .main-container .content2 .address{
            height: auto;
            width: 50%;
            border: 2px solid black;
            padding: 20px;
        }
        @media screen and (max-width: 950px) {
            .main-container .content .part1{
                width: 60%;
                height: auto;
            }
            .main-container .content .part2{
                height: auto;
                width: 100%;
            }
        }
        @media screen and (max-width: 800px) {
            .main-container .content .part1{
                width: 80%;
                height: auto;
            }
        }
        @media screen and (max-width: 767px) {
            .main-container{
                margin-left: 0;
            }
            .main-container .content2 .address{
                width: 100%;
            }
        }
        @media screen and (max-width: 400px) {
            .main-container .content .part1{
                width: 95%;
                height: auto;
            }
        }
    </style>
    {% endblock %}
</head>
<body>
    {% block body %} 
    <div class="main-container">
        <h2>About Us</h2>
        <div class="content">
            <div class="part1" style="padding: 20px;">
                <img src="{% static 'images/construction-08.jpg' %}" alt="">
            </div>
            <div class="part2">
                <h5>We are energetic about discovering things that transcend the commonplace; that we think will get your attention and capture it. In addition, to convey these to you wherever you are and at whatever point you believe you have sufficient energy to enjoy a bit.
                    <br><br>
                    So we made an organization to bring you items you will become hopelessly enamored with; to allow you to make your very own space, to take advantage of those concealed abilities and make your own looks and accumulations; to enable you to impart your manifestations to companions to understand that second conclusion, to move or be enlivened; and to enable you to shop such that you will discover hypnotizing.
                    <br><br>
                    We like to consider 'Libass Of India' as the advanced age likeness the sixteenth Century Grand Trunk Road, an expressway that changed the essence of exchange the US subcontinent.
                    </h5>
            </div>
        </div>
    </div>   
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>

</html>
{% block script %}
{% endblock %}

Mainpage/templates/Mainpage/add-design.html
{% extends 'Mainpage/basic.html' %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
    Add Design - Thanks for joining with us
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% block style %}
    <link rel="stylesheet" href="{% static 'css/consultation.css' %}">
    <style>
        .jd{
            color:red;
            font-size:10px;
        }
    </style>
    {% endblock %}
</head>

<body>
    {% block body %}
    
    <main>
        {% if messages %}
    <ul class="messages" id="message" style="margin-top: 100px;">
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </ul>
    {% endif %}
        <div class="modal fade" id="postmodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Design Content</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="/add-design/" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="modal-body">
                            <div class="mb-3">
                                <label for="" class="form-label">Design Image</label>
                                <span class="jd">**please select image having less than 2 Mb of size.</span>
                                <input type="file" class="form-control" name="design_img" id="id_design_img" required>
                            </div>
                            <div class="mb-3">
                                <label for="" class="form-label">Project Name</label>
                                <input type="text" class="form-control" name="project_name" id="" required>
                            </div>
                            <div class="mb-3">
                                <label for="" class="form-label">Design Type</label>
                                <input type="text" class="form-control" name="design_type" id="" required>
                            </div>
                            <div class="mb-3">
                                <label for="" class="form-label">Design Description</label>
                                <textarea class="form-control" id="" name="design_desc" rows="3" required></textarea>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" style="padding: 10px;"
                                data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary" style="padding: 10px;">POST</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="post-btn">
                <button class="custom-btn btn-3" data-bs-toggle="modal" data-bs-target="#postmodal"><span>Add
                        Design</span></button>
                
            </div>

            <!-- <div class="content">
                {% for i in customer_data %}
                <a href="">
                    <div class="contain">
                        <div class="images">
                            <div class="userimg">
                                <i style='font-size:100px; color: black;' class='fas'>&#xf406;</i>
                            </div>
                        </div>
                        <div class="userdetails">
                            <h5>{{i.first_name}} {{i.last_name}}</h5>
                            <h5>{{i.email}}</h5>
                            <h5>{{i.mobile}}</h5>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div> -->
        </div>
    </main>
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>

</html>
{% block script %}
<script>
    var upload_field = document.getElementById("id_design_img");

    upload_field.onchange = function () {
        if (this.files[0].size > 1048576) {
            this.value = "";
            document.getElementById("error_form").innerText = "File size must be less than 1 MB";
        }
        else {
            document.getElementById("error_form").innerText = "";
        }
    }
</script>
{% endblock %}

Mainpage/templates/Mainpage/all_user.html
{% extends 'Mainpage/basic.html' %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
    {% if type == 'Consumer' %}
    All architecture - profiles
    {% else %}
    All Consumers - Profiles
    {% endif %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% block style %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <style>
        .containers {
            display: flex;
            flex-wrap: wrap;
            margin-top: 30px;
            justify-content: center;
            align-items: center;
            margin-bottom: 30px;
        }
        .containers a{
            width: 80%;
        }
        .containers .userprofile {
            width: 100%;
            margin-top: 20px;
            display: flex;
            padding: 20px;
        }

        .containers .userprofile .images {
            width: 20%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .containers .userprofile .userdetails {
            width: 50%;
        }

        .containers .userprofile .editbtn {
            width: 30%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .main {
            margin-top: 30px;
            display: flex;
            justify-content: center;
            align-items: center;
            margin-bottom: 20px;
        }

        .main .myorder {
            width: 80%;
            padding: 20px;
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
            border-radius: 20px;
        }

        .main .myorder .order {
            margin-top: 20px;
            display: flex;
            flex-wrap: wrap;
            border: 1px solid black;
            border-radius: 10px;
        }

        .main .myorder .order .part1 {
            width: 30%;
            padding: 10px;
        }

        .main .myorder .order .part2 {
            padding: 20px;
            width: 70%;
        }

        @media screen and (max-width: 650px) {
            .main .myorder .order .part1 {
                width: 100%;
            }

            .main .myorder .order .part2 {
                width: 100%;
            }
        }

        .logout-btn {
            padding-left: 150px;
            padding-right: 150px;
        }

        @media screen and (max-width: 768px) {
            .containers .userprofile {
                height: 400px;
                padding: 0;
                flex-wrap: wrap;
            }

            .containers .userprofile .images {
                height: 35%;
                width: 100%;
            }

            .containers .userprofile .userdetails {
                height: 35%;
                width: 100%;
                text-align: center;
            }
        }
    </style>
    {% endblock %}
</head>

<body>
    {% block body %}
    {% if messages %}
    <ul class="messages" id="message">
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    {% if type == "Consumer" %}
    <h2 style="text-align: center; margin-top: 130px;">All Architects</h2>
    {% else %}
    <h2 style="text-align: center; margin-top: 130px;">All Consumers</h2>
    {% endif %}
    <div class="containers">
        {% for i in user_list %}
            <a href="/user-info/{{i.id}}/">
                <div class="userprofile" style="box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px; border-radius: 20px;">
                    <div class="images">
                        <div class="userimg">
                            <i style='font-size:100px' class='fas'>&#xf406;</i>
                        </div>
                    </div>
                    <div class="userdetails">
                        <h5>{{i.first_name}} {{i.last_name}}</h5>
                        <h5>{{i.email}}</h5>
                        <h5>{{i.number}}</h5>
                        <h5>{{i.acc_type}}</h5>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>

</html>
{% block script %}
<script>

</script>
{% endblock %}

Mainpage/templates/Mainpage/design.html
{% extends 'Mainpage/basic.html' %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %} Top Designs - ArcDesk {% endblock %}
    <link href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% block style %}
    <link rel="stylesheet" href="{% static 'css/design.css' %}">
    {% endblock %}
</head>

<body>
    {% block body %}
    <main>
        <div class="container">
            <h2>Top Designs</h2>
            {% if design_data %}
            {% for i in design_data %}
            <div class="content">
                <div class="part1"><img src="/media/{{i.design_img}}" alt=""></div>
                <a href="/mydesign/{{i.id}}">
                    <div class="part2">
                        <h3>{{i.project_name}}</h3><br>
                        <h5>Design Type - {{i.design_type}}</h5><br>
                        <p style="color: black;">{{i.design_desc|slice:":150" }}... <a href="/mydesign/{{i.id}}" style="color: black;">Read more</a></p>
                    </div>
                </a>
            </div>
            {% endfor %}
            {% else %}
            <p>No any Designs yet!!</p>
            {% endif %}
        </div>
    </main>
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>

</html>
{% block script %}
{% endblock %}